project     = "INSERT PROJECT ID HERE"
region      = "INSERT REGION ie us-central1"
zone        = "INSERT ZONE ie us-central1-a"
cluster_name = "INSERT CLUSTER NAME HERE"
public_ip   = "INSERT YOUR IP HERE"
