---
- name: Deploy Jenkins on GKE
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Authenticate with GKE
      shell: |
        gcloud container clusters get-credentials {{ cluster_name }} --zone {{ zone }} --project {{ project }}
      environment:
        CLOUDSDK_CORE_PROJECT: "{{ project }}"

    - name: Create Jenkins namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: jenkins

    - name: Apply Jenkins PVC
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'jenkins_pvc.yaml') }}"

    - name: Apply Jenkins ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'jenkins-role-binding.yaml') }}"

    - name: Deploy Jenkins with Persistent Disk
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'jenkins_deployment.yaml') }}"

    - name: Create Jenkins Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'jenkins_service.yaml') }}"
