---
- name: Deploy Jenkins on GKE using Helm
  hosts: localhost
  gather_facts: no
  tasks:
- name: Authenticate with GKE
      shell: |
        gcloud container clusters get-credentials {{ cluster_name }} --zone {{ zone }} --project {{ project }}
      environment:
        CLOUDSDK_CORE_PROJECT: "{{ project }}"
- name: Add Jenkins Helm repo
      kubernetes.core.helm_repository:
        name: jenkins
        repo_url: "https://charts.jenkins.io"
- name: Deploy Jenkins using Helm
      kubernetes.core.helm:
        name: jenkins
        chart_ref: jenkins/jenkins
        release_namespace: jenkins
        create_namespace: true
        values:
          controller:
            serviceType: LoadBalancer
          persistence:
            storageClass: "standard"
            size: 50Gi
          rbac:
            create: true
            clusterAdminRole: true
