---
- name: Deploy Jenkins on GKE using Helm
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Authenticate with GKE
      shell: |
        gcloud container clusters get-credentials {{ cluster_name }} --zone {{ zone }} --project {{ project }}
      environment:
        CLOUDSDK_CORE_PROJECT: "{{ project }}"
    # Add debug tasks here, right after authentication
    - name: Debug - Display variables
      debug:
        msg: "Project: {{ project }}, Zone: {{ zone }}, Cluster: {{ cluster_name }}"

    - name: Debug - Check kubectl access
      shell: kubectl get nodes
      register: kubectl_result
      ignore_errors: yes

    - name: Display kubectl result
      debug:
        var: kubectl_result

    - name: Check Helm version
      shell: helm version
      register: helm_version
      ignore_errors: yes

    - name: Display Helm version
      debug:
        var: helm_version

    - name: Add Jenkins Helm repo
      kubernetes.core.helm_repository:
        name: jenkins
        repo_url: "https://charts.jenkins.io"

    - name: Deploy Jenkins using Helm
      kubernetes.core.helm:
        name: jenkins
        chart_ref: jenkins/jenkins
        release_namespace: jenkins
        create_namespace: true
        values:
          controller:
            serviceType: LoadBalancer
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          persistence:
            storageClass: "standard"
            size: 50Gi
          rbac:
            create: true
            clusterAdminRole: true
          agent:
            enabled: true
            componentName: "jenkins-agent"
            image:
              repository: "jenkins/inbound-agent"
              tag: "latest-alpine3.20-jdk21"  
            workingDir: "/home/jenkins/agent"
            containerCap: 10
            podName: "default"
            customJenkinsLabels: []
            resources:
              requests:
                cpu: "512m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
          additionalAgents:
            maven:
              podName: maven
              customJenkinsLabels: maven
              image:
              repository: jenkins/inbound-agent
              tag: "latest-alpine3.20-jdk21"  # Using the same latest image for Maven
            python:
              podName: python
              customJenkinsLabels: python
              image:
                repository: jenkins/inbound-agent
                tag: "latest-alpine3.20-jdk21"  # Using the same latest image for Python